# Количество реплик Nginx
replicaCount: 2

# Nginx
nginx:
  image:
    repository: ghcr.io/petro-bulka/my-infra-lab
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

# Ingress
ingress:
  enabled: true
  className: traefik
  host: my-infra-lab.local
  path: /

# PostgreSQL
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 15-alpine
  auth:
    username: admin
    password: secretpassword
    database: mydb
  persistence:
    size: 2Gi
