global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets:
          - '192.168.1.98:9100'   # VM1
          - '192.168.1.124:9100'  # VM2
          - '192.168.1.99:9100'   # VM3
